# Generated by Django 6.0.7 on 2026-07-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.BigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Global Identifier",
                "verbose_name_plural": "Global Identifiers",
            },
        ),
    ]
