# Generated by Django 6.0.7 on 2026-07-20 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Bezeichnung")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default-product-image.jpg",
                        null=True,
                        upload_to="image/items",
                        verbose_name="Artikelbild",
                    ),
                ),
                (
                    "manufacturer_number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Hersteller Artikelnummer",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preis netto"
                    ),
                ),
                ("tax", models.IntegerField(default=19, verbose_name="MwSt.")),
                (
                    "unit",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Stück"), (2, "Meter"), (3, "Rolle")],
                        default=1,
                        verbose_name="Maßeinheit",
                    ),
                ),
                (
                    "on_stock",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Lagerbestand"
                    ),
                ),
                (
                    "min_stock",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Mindestbestand"
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="EAN"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="orders.category",
                        verbose_name="Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artikel",
                "verbose_name_plural": "Artikeln",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=256, null=True, verbose_name="Notiz"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bestellung",
                "verbose_name_plural": "Bestellungen",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Menge"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="orders.item",
                        verbose_name="Artikel",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Auftrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artikel",
                "verbose_name_plural": "Artikeln",
            },
        ),
    ]
