# Generated by Django 6.0.7 on 2026-07-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_item_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="tax",
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preis"
            ),
        ),
    ]
