# Generated by Django 6.0.7 on 2026-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_stripe_checkout_order_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(
                db_index=True, default=1, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
