# Generated by Django 6.0.7 on 2026-07-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_stripe_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('id',), 'verbose_name': 'Bestellposition', 'verbose_name_plural': 'Bestellpositionen'},
        ),
    ]
