# Generated by Django 6.0.8 on 2026-08-29 11:10

from django.db import migrations


class Migration(migrations.Migration):
    """
    Behebt eine bereits vor diesem Feature bestehende Abweichung zwischen
    Migration 0008 (ordering=("id",)) und dem tatsächlichen Modellstand
    (ordering=("order_id",)) - unabhängig von ADR 0009/0010/0011, aber von
    makemigrations mitdetektiert und daher in einer eigenen, klar
    abgegrenzten Migration nachgezogen.
    """

    dependencies = [
        ("orders", "0008_orderitem_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ("order_id",),
                "verbose_name": "Bestellposition",
                "verbose_name_plural": "Bestellpositionen",
            },
        ),
    ]
