# Generated by Django 6.0.8 on 2026-08-29 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_orderitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Zeitpunkt des Zahlungseingangs, gesetzt von OrderService.mark_as_paid(). Anders als modified_at nicht bei jedem Save betroffen, daher als Leistungsdatum für Rechnungen geeignet (§14 Abs. 4 Nr. 6 UStG).",
                null=True,
                verbose_name="bezahlt am",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Rechnung"),
                            ("credit_note", "Gutschrift/Korrekturrechnung"),
                        ],
                        default="invoice",
                        max_length=16,
                        verbose_name="Dokumenttyp",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Grund"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Rechnungsnummer",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ausgestellt am"
                    ),
                ),
                (
                    "service_date",
                    models.DateField(
                        editable=False,
                        help_text="Tag der Vereinnahmung des Entgelts (§14 Abs. 4 Nr. 6 UStG), da Zahlung vor Lieferung erfolgt.",
                        verbose_name="Leistungsdatum",
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        editable=False, max_length=160, verbose_name="Käufer"
                    ),
                ),
                (
                    "buyer_street",
                    models.CharField(
                        editable=False, max_length=255, verbose_name="Käufer Straße"
                    ),
                ),
                (
                    "buyer_zip",
                    models.CharField(
                        editable=False, max_length=16, verbose_name="Käufer PLZ"
                    ),
                ),
                (
                    "buyer_city",
                    models.CharField(
                        editable=False, max_length=128, verbose_name="Käufer Ort"
                    ),
                ),
                (
                    "buyer_country",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="Käufer Land"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Nettobetrag",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=3,
                        editable=False,
                        max_digits=4,
                        verbose_name="Steuersatz",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Steuerbetrag",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Gesamtbetrag",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        editable=False,
                        upload_to="invoices/%Y/",
                        verbose_name="PDF-Datei",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="versendet am",
                    ),
                ),
                (
                    "credited_invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nur gesetzt bei document_type=credit_note: referenzierte Ursprungsrechnung.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="orders.invoice",
                        verbose_name="korrigierte Rechnung",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="orders.order",
                        verbose_name="Bestellung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
                "ordering": ("-issued_at",),
            },
        ),
    ]
