# Generated by Django 6.0.8 on 2026-08-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_paid_at_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="carrier",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Versanddienstleister",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="zugestellt am"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ausstehend"),
                    ("processing", "In Bearbeitung"),
                    ("shipped", "Versandt"),
                    ("delivered", "Zugestellt"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="Versandstatus",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="versandt am"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Sendungsnummer"
            ),
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[
                            ("payment", "Zahlungsstatus"),
                            ("fulfillment", "Versandstatus"),
                        ],
                        max_length=16,
                        verbose_name="Status-Art",
                    ),
                ),
                (
                    "old_value",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="alter Wert"
                    ),
                ),
                (
                    "new_value",
                    models.CharField(max_length=32, verbose_name="neuer Wert"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Notiz"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="geändert am"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff-Nutzer bei manueller Änderung, None bei automatischen (z. B. Webhook-getriebenen) Übergängen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="geändert von",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                        verbose_name="Bestellung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bestellstatus-Verlauf",
                "verbose_name_plural": "Bestellstatus-Verläufe",
                "ordering": ("changed_at",),
            },
        ),
    ]
