# Generated by Django 6.0.8 on 2026-08-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_carrier_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmation_sent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Bestellbestätigung versendet am",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Versand-Benachrichtigung versendet am",
            ),
        ),
    ]
