# Generated by Django 6.0.8 on 2026-08-29 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_transactional_emails_order_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Angefragt"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                            ("refunded", "Erstattet"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("reason", models.TextField(max_length=500, verbose_name="Grund")),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="angefragt am"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="entschieden am"
                    ),
                ),
                (
                    "rejection_note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Ablehnungsgrund",
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="erstattet am"
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="entschieden von",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="orders.order",
                        verbose_name="Bestellung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rückgabeanfrage",
                "verbose_name_plural": "Rückgabeanfragen",
                "ordering": ("-requested_at",),
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(verbose_name="Menge")),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="orders.orderitem",
                        verbose_name="Bestellposition",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.returnrequest",
                        verbose_name="Rückgabeanfrage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rückgabeposition",
                "verbose_name_plural": "Rückgabepositionen",
                "ordering": ("return_request_id",),
            },
        ),
    ]
