# Generated by Django 6.0.7 on 2026-07-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_globalidentifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(default=1, max_length=255, verbose_name="Ort"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                default="Deutschland", max_length=255, verbose_name="Land"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="street",
            field=models.CharField(default=1, max_length=255, verbose_name="Straße"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="street_no",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Hausnummer"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="zip_code",
            field=models.CharField(default=1, max_length=5, verbose_name="PLZ"),
            preserve_default=False,
        ),
    ]
