# Generated by Django 6.0.7 on 2026-07-28 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0004_customuser_city_customuser_country_customuser_street_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="GlobalIdentifier",
        ),
    ]
