# Generated by Django 6.0.8 on 2026-08-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_alter_customuser_email_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notifications_last_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Gesetzt von UserMeViewSet.mark_notifications_seen() - Ereignisse mit occurred_at danach gelten als ungelesen (siehe ADR 0021). None bedeutet: alle Ereignisse sind ungelesen.",
                null=True,
                verbose_name="Benachrichtigungen zuletzt gesehen am",
            ),
        ),
    ]
